### ISSUE TITLE
役割の割り当てが上手くいっていない。

### ISSUE THREAD

**Issue by kotaro-yamasaki** [thirdlf03/matching#110]
役割の担当者をデフォルトの人から変更してもう一度選び直せばいけるけど、選択肢が一人(作成者のみ)や二人の場合は選択肢を変更することができないため割り当てができない。
デフォルトで「担当者を選ぶ」などの値を入れたらいけるかも。
ルームの作成者自身を割り当てられない。

**Comment by kotaro-yamasaki** [comment]
developだと作成もできなくなった

**Comment by thirdlf03** [comment]
修正済み
